import type { SpecialistDTO } from "@/features/specialist/model/types";

type SpecialistMock = SpecialistDTO;

export const specialistData: SpecialistMock[] = [
    {
        id: "spec-1",
        firstName: "Maya",
        lastName: "Levi",
        phoneNumber: "+972501234567",
        photoUrl: null,
        birthDate: "2024-06-10T09:00:00.000Z",
        gender: "female",
        languages: ["he", "en"],
        profession: "psychologist",
        meetingFormat: "online",
        experience: 9,
        pricePerSession: 120,
        services: ["Anxiety", "Stress", "PTSD"],
    },
    {
        id: "spec-2",
        firstName: "Alex",
        lastName: "Petrov",
        phoneNumber: "+972541234567",
        photoUrl: null,
        birthDate: "2024-06-10T09:00:00.000Z",
        gender: "male",
        languages: ["ru", "en"],
        profession: "therapist",
        meetingFormat: "online",
        experience: 12,
        pricePerSession: 180,
        services: ["Depression", "Burnout", "Self-esteem"],
    },
    {
        id: "spec-3",
        firstName: "Nadia",
        lastName: "Koval",
        phoneNumber: "+972521234567",
        photoUrl: null,
        birthDate: "2024-06-10T09:00:00.000Z",
        gender: "female",
        languages: ["uk", "ru"],
        profession: "coach",
        meetingFormat: "offline",
        experience: 6,
        pricePerSession: 140,
        services: ["Life goals", "Career", "Motivation"],
    },
    {
        id: "spec-4",
        firstName: "Omar",
        lastName: "Hassan",
        phoneNumber: "+972531234567",
        photoUrl: null,
        birthDate: "2024-06-10T09:00:00.000Z",
        gender: "male",
        languages: ["ar", "en"],
        profession: "therapist",
        meetingFormat: "online",
        experience: 10,
        pricePerSession: 200,
        services: ["Family therapy", "Relationships", "Anger"],
    },
    {
        id: "spec-5",
        firstName: "Lina",
        lastName: "Cohen",
        phoneNumber: "+972551234567",
        photoUrl: null,
        birthDate: "2024-06-10T09:00:00.000Z",
        gender: "female",
        languages: ["he", "ru", "en"],
        profession: "psychologist",
        meetingFormat: "offline",
        experience: 8,
        pricePerSession: 160,
        services: ["Trauma", "Sleep", "Mindfulness"],
    },
    {
        id: "spec-6",
        firstName: "David",
        lastName: "Shapiro",
        phoneNumber: "+972502234567",
        photoUrl: null,
        birthDate: "1985-03-15T00:00:00.000Z",
        gender: "male",
        languages: ["he", "en"],
        profession: "psychologist",
        meetingFormat: "online",
        experience: 11,
        pricePerSession: 220,
        services: ["Anxiety", "OCD", "Phobias"],
    },
    {
        id: "spec-7",
        firstName: "Elena",
        lastName: "Volkov",
        phoneNumber: "+972503234567",
        photoUrl: null,
        birthDate: "1990-07-22T00:00:00.000Z",
        gender: "female",
        languages: ["ru", "en"],
        profession: "therapist",
        meetingFormat: "offline",
        experience: 7,
        pricePerSession: 150,
        services: ["Depression", "Grief", "Life transitions"],
    },
    {
        id: "spec-8",
        firstName: "Yael",
        lastName: "Ben-David",
        phoneNumber: "+972504234567",
        photoUrl: null,
        birthDate: "1988-11-08T00:00:00.000Z",
        gender: "female",
        languages: ["he", "en", "ru"],
        profession: "psychologist",
        meetingFormat: "online",
        experience: 14,
        pricePerSession: 260,
        services: ["PTSD", "Trauma", "Anxiety"],
    },
    {
        id: "spec-9",
        firstName: "Michael",
        lastName: "Rosenberg",
        phoneNumber: "+972505234567",
        photoUrl: null,
        birthDate: "1982-01-30T00:00:00.000Z",
        gender: "male",
        languages: ["he", "en"],
        profession: "coach",
        meetingFormat: "online",
        experience: 5,
        pricePerSession: 130,
        services: ["Career", "Leadership", "Productivity"],
    },
    {
        id: "spec-10",
        firstName: "Svetlana",
        lastName: "Kozlov",
        phoneNumber: "+972506234567",
        photoUrl: null,
        birthDate: "1979-09-12T00:00:00.000Z",
        gender: "female",
        languages: ["ru", "uk", "en"],
        profession: "therapist",
        meetingFormat: "offline",
        experience: 18,
        pricePerSession: 280,
        services: ["Family therapy", "Couples", "Parenting"],
    },
    {
        id: "spec-11",
        firstName: "Ahmad",
        lastName: "Khalil",
        phoneNumber: "+972507234567",
        photoUrl: null,
        birthDate: "1992-04-25T00:00:00.000Z",
        gender: "male",
        languages: ["ar", "he", "en"],
        profession: "psychologist",
        meetingFormat: "online",
        experience: 6,
        pricePerSession: 145,
        services: ["Stress", "Identity", "Cultural issues"],
    },
    {
        id: "spec-12",
        firstName: "Tamar",
        lastName: "Goldstein",
        phoneNumber: "+972508234567",
        photoUrl: null,
        birthDate: "1987-12-03T00:00:00.000Z",
        gender: "female",
        languages: ["he", "en"],
        profession: "psychologist",
        meetingFormat: "online",
        experience: 9,
        pricePerSession: 190,
        services: ["Eating disorders", "Body image", "Self-esteem"],
    },
    {
        id: "spec-13",
        firstName: "Dmitry",
        lastName: "Sokolov",
        phoneNumber: "+972509234567",
        photoUrl: null,
        birthDate: "1984-06-18T00:00:00.000Z",
        gender: "male",
        languages: ["ru", "en"],
        profession: "coach",
        meetingFormat: "offline",
        experience: 8,
        pricePerSession: 165,
        services: ["Motivation", "Goals", "Habits"],
    },
    {
        id: "spec-14",
        firstName: "Rachel",
        lastName: "Levy",
        phoneNumber: "+972510234567",
        photoUrl: null,
        birthDate: "1991-02-14T00:00:00.000Z",
        gender: "female",
        languages: ["he", "en", "ru"],
        profession: "therapist",
        meetingFormat: "online",
        experience: 4,
        pricePerSession: 110,
        services: ["Anxiety", "Panic", "Social anxiety"],
    },
    {
        id: "spec-15",
        firstName: "Igor",
        lastName: "Petrenko",
        phoneNumber: "+972511234567",
        photoUrl: null,
        birthDate: "1976-08-07T00:00:00.000Z",
        gender: "male",
        languages: ["uk", "ru", "en"],
        profession: "psychologist",
        meetingFormat: "offline",
        experience: 20,
        pricePerSession: 300,
        services: ["Addiction", "PTSD", "Depression"],
    },
    {
        id: "spec-16",
        firstName: "Noa",
        lastName: "Friedman",
        phoneNumber: "+972512234567",
        photoUrl: null,
        birthDate: "1993-05-20T00:00:00.000Z",
        gender: "female",
        languages: ["he", "en"],
        profession: "coach",
        meetingFormat: "online",
        experience: 3,
        pricePerSession: 100,
        services: ["Work-life balance", "Burnout", "Stress"],
    },
    {
        id: "spec-17",
        firstName: "Viktor",
        lastName: "Orlov",
        phoneNumber: "+972513234567",
        photoUrl: null,
        birthDate: "1980-10-11T00:00:00.000Z",
        gender: "male",
        languages: ["ru", "en"],
        profession: "therapist",
        meetingFormat: "online",
        experience: 13,
        pricePerSession: 240,
        services: ["Depression", "Anxiety", "Relationships"],
    },
    {
        id: "spec-18",
        firstName: "Hannah",
        lastName: "Weiss",
        phoneNumber: "+972514234567",
        photoUrl: null,
        birthDate: "1989-03-28T00:00:00.000Z",
        gender: "female",
        languages: ["he", "en", "ar"],
        profession: "psychologist",
        meetingFormat: "offline",
        experience: 10,
        pricePerSession: 205,
        services: ["Child psychology", "ADHD", "Learning difficulties"],
    },
    {
        id: "spec-19",
        firstName: "Sergey",
        lastName: "Ivanov",
        phoneNumber: "+972515234567",
        photoUrl: null,
        birthDate: "1983-07-05T00:00:00.000Z",
        gender: "male",
        languages: ["ru", "uk", "en"],
        profession: "coach",
        meetingFormat: "offline",
        experience: 6,
        pricePerSession: 142,
        services: ["Career change", "Interview skills", "Networking"],
    },
    {
        id: "spec-20",
        firstName: "Miriam",
        lastName: "Cohen",
        phoneNumber: "+972516234567",
        photoUrl: null,
        birthDate: "1978-11-19T00:00:00.000Z",
        gender: "female",
        languages: ["he", "en"],
        profession: "therapist",
        meetingFormat: "online",
        experience: 16,
        pricePerSession: 270,
        services: ["Trauma", "EMDR", "PTSD"],
    },
    {
        id: "spec-21",
        firstName: "Andrey",
        lastName: "Morozov",
        phoneNumber: "+972517234567",
        photoUrl: null,
        birthDate: "1994-01-09T00:00:00.000Z",
        gender: "male",
        languages: ["ru", "en"],
        profession: "psychologist",
        meetingFormat: "online",
        experience: 4,
        pricePerSession: 115,
        services: ["Youth", "Identity", "Anxiety"],
    },
    {
        id: "spec-22",
        firstName: "Sarah",
        lastName: "Mizrahi",
        phoneNumber: "+972518234567",
        photoUrl: null,
        birthDate: "1986-04-16T00:00:00.000Z",
        gender: "female",
        languages: ["he", "en", "ru"],
        profession: "psychologist",
        meetingFormat: "offline",
        experience: 12,
        pricePerSession: 225,
        services: ["Perinatal", "Postpartum", "Parenting"],
    },
    {
        id: "spec-23",
        firstName: "Oleg",
        lastName: "Kuznetsov",
        phoneNumber: "+972519234567",
        photoUrl: null,
        birthDate: "1981-12-22T00:00:00.000Z",
        gender: "male",
        languages: ["ru", "uk", "en"],
        profession: "therapist",
        meetingFormat: "online",
        experience: 11,
        pricePerSession: 215,
        services: ["Anger", "Stress", "Communication"],
    },
    {
        id: "spec-24",
        firstName: "Leah",
        lastName: "Berger",
        phoneNumber: "+972520234567",
        photoUrl: null,
        birthDate: "1990-06-30T00:00:00.000Z",
        gender: "female",
        languages: ["he", "en"],
        profession: "coach",
        meetingFormat: "online",
        experience: 7,
        pricePerSession: 155,
        services: ["Confidence", "Public speaking", "Assertiveness"],
    },
    {
        id: "spec-25",
        firstName: "Rami",
        lastName: "Elkabetz",
        phoneNumber: "+972521234567",
        photoUrl: null,
        birthDate: "1985-09-14T00:00:00.000Z",
        gender: "male",
        languages: ["he", "ar", "en"],
        profession: "psychologist",
        meetingFormat: "offline",
        experience: 9,
        pricePerSession: 185,
        services: ["Men's issues", "Relationships", "Anxiety"],
    },
    {
        id: "spec-26",
        firstName: "Olga",
        lastName: "Romanova",
        phoneNumber: "+972522234567",
        photoUrl: null,
        birthDate: "1987-02-28T00:00:00.000Z",
        gender: "female",
        languages: ["ru", "en"],
        profession: "therapist",
        meetingFormat: "offline",
        experience: 8,
        pricePerSession: 170,
        services: ["Depression", "Self-esteem", "Boundaries"],
    },
    {
        id: "spec-27",
        firstName: "Jonathan",
        lastName: "Stern",
        phoneNumber: "+972523234567",
        photoUrl: null,
        birthDate: "1979-08-03T00:00:00.000Z",
        gender: "male",
        languages: ["he", "en"],
        profession: "psychologist",
        meetingFormat: "online",
        experience: 15,
        pricePerSession: 265,
        services: ["Existential", "Meaning", "Life crises"],
    },
    {
        id: "spec-28",
        firstName: "Kateryna",
        lastName: "Shevchenko",
        phoneNumber: "+972524234567",
        photoUrl: null,
        birthDate: "1992-10-17T00:00:00.000Z",
        gender: "female",
        languages: ["uk", "ru", "en"],
        profession: "coach",
        meetingFormat: "online",
        experience: 5,
        pricePerSession: 135,
        services: ["Mindfulness", "Resilience", "Emotional regulation"],
    },
    {
        id: "spec-29",
        firstName: "Youssef",
        lastName: "Nassar",
        phoneNumber: "+972525234567",
        photoUrl: null,
        birthDate: "1984-05-24T00:00:00.000Z",
        gender: "male",
        languages: ["ar", "he", "en"],
        profession: "therapist",
        meetingFormat: "offline",
        experience: 10,
        pricePerSession: 195,
        services: ["Family", "Conflict", "Cross-cultural"],
    },
    {
        id: "spec-30",
        firstName: "Rivka",
        lastName: "Adler",
        phoneNumber: "+972526234567",
        photoUrl: null,
        birthDate: "1986-01-12T00:00:00.000Z",
        gender: "female",
        languages: ["he", "en"],
        profession: "psychologist",
        meetingFormat: "online",
        experience: 11,
        pricePerSession: 218,
        services: ["OCD", "Anxiety", "Phobias"],
    },
    {
        id: "spec-31",
        firstName: "Pavel",
        lastName: "Volkov",
        phoneNumber: "+972527234567",
        photoUrl: null,
        birthDate: "1991-07-08T00:00:00.000Z",
        gender: "male",
        languages: ["ru", "en"],
        profession: "coach",
        meetingFormat: "offline",
        experience: 4,
        pricePerSession: 112,
        services: ["Startup mindset", "Decision making", "Focus"],
    },
    {
        id: "spec-32",
        firstName: "Anna",
        lastName: "Smirnova",
        phoneNumber: "+972528234567",
        photoUrl: null,
        birthDate: "1988-11-25T00:00:00.000Z",
        gender: "female",
        languages: ["ru", "he", "en"],
        profession: "therapist",
        meetingFormat: "online",
        experience: 9,
        pricePerSession: 188,
        services: ["Grief", "Loss", "Chronic illness"],
    },
    {
        id: "spec-33",
        firstName: "Daniel",
        lastName: "Katz",
        phoneNumber: "+972529234567",
        photoUrl: null,
        birthDate: "1982-04-02T00:00:00.000Z",
        gender: "male",
        languages: ["he", "en"],
        profession: "psychologist",
        meetingFormat: "offline",
        experience: 14,
        pricePerSession: 255,
        services: ["Sport psychology", "Performance", "Anxiety"],
    },
    {
        id: "spec-34",
        firstName: "Marina",
        lastName: "Kravchenko",
        phoneNumber: "+972530234567",
        photoUrl: null,
        birthDate: "1993-09-19T00:00:00.000Z",
        gender: "female",
        languages: ["uk", "ru", "en"],
        profession: "psychologist",
        meetingFormat: "online",
        experience: 6,
        pricePerSession: 148,
        services: ["Depression", "Anxiety", "Sleep"],
    },
    {
        id: "spec-35",
        firstName: "Eitan",
        lastName: "Barak",
        phoneNumber: "+972531234567",
        photoUrl: null,
        birthDate: "1977-12-06T00:00:00.000Z",
        gender: "male",
        languages: ["he", "en"],
        profession: "therapist",
        meetingFormat: "online",
        experience: 19,
        pricePerSession: 290,
        services: ["Couples", "Sex therapy", "Intimacy"],
    },
    {
        id: "spec-36",
        firstName: "Inna",
        lastName: "Bondarenko",
        phoneNumber: "+972532234567",
        photoUrl: null,
        birthDate: "1989-03-11T00:00:00.000Z",
        gender: "female",
        languages: ["uk", "ru", "en"],
        profession: "coach",
        meetingFormat: "offline",
        experience: 8,
        pricePerSession: 168,
        services: ["Time management", "Priorities", "Delegation"],
    },
    {
        id: "spec-37",
        firstName: "Moshe",
        lastName: "Golan",
        phoneNumber: "+972533234567",
        photoUrl: null,
        birthDate: "1980-06-27T00:00:00.000Z",
        gender: "male",
        languages: ["he", "en", "ru"],
        profession: "psychologist",
        meetingFormat: "offline",
        experience: 13,
        pricePerSession: 245,
        services: ["Addiction", "Recovery", "Relapse prevention"],
    },
    {
        id: "spec-38",
        firstName: "Valentina",
        lastName: "Fedorova",
        phoneNumber: "+972534234567",
        photoUrl: null,
        birthDate: "1985-02-14T00:00:00.000Z",
        gender: "female",
        languages: ["ru", "en"],
        profession: "therapist",
        meetingFormat: "online",
        experience: 10,
        pricePerSession: 198,
        services: ["Borderline", "Attachment", "DBT"],
    },
    {
        id: "spec-39",
        firstName: "Guy",
        lastName: "Peretz",
        phoneNumber: "+972535234567",
        photoUrl: null,
        birthDate: "1994-08-21T00:00:00.000Z",
        gender: "male",
        languages: ["he", "en"],
        profession: "coach",
        meetingFormat: "online",
        experience: 3,
        pricePerSession: 105,
        services: ["Personal branding", "LinkedIn", "Career growth"],
    },
    {
        id: "spec-40",
        firstName: "Natalia",
        lastName: "Sidorova",
        phoneNumber: "+972536234567",
        photoUrl: null,
        birthDate: "1983-10-05T00:00:00.000Z",
        gender: "female",
        languages: ["ru", "uk", "en"],
        profession: "psychologist",
        meetingFormat: "offline",
        experience: 12,
        pricePerSession: 230,
        services: ["Elderly", "Retirement", "Aging"],
    },
    {
        id: "spec-41",
        firstName: "Tal",
        lastName: "Avraham",
        phoneNumber: "+972537234567",
        photoUrl: null,
        birthDate: "1990-05-18T00:00:00.000Z",
        gender: "female",
        languages: ["he", "en"],
        profession: "psychologist",
        meetingFormat: "online",
        experience: 7,
        pricePerSession: 158,
        services: ["LGBTQ+", "Identity", "Relationships"],
    },
    {
        id: "spec-42",
        firstName: "Maxim",
        lastName: "Popov",
        phoneNumber: "+972538234567",
        photoUrl: null,
        birthDate: "1987-01-23T00:00:00.000Z",
        gender: "male",
        languages: ["ru", "en"],
        profession: "therapist",
        meetingFormat: "offline",
        experience: 9,
        pricePerSession: 182,
        services: ["Procrastination", "Perfectionism", "Self-criticism"],
    },
    {
        id: "spec-43",
        firstName: "Shira",
        lastName: "Dahan",
        phoneNumber: "+972539234567",
        photoUrl: null,
        birthDate: "1988-07-30T00:00:00.000Z",
        gender: "female",
        languages: ["he", "en", "ar"],
        profession: "coach",
        meetingFormat: "online",
        experience: 6,
        pricePerSession: 138,
        services: ["Women leadership", "Negotiation", "Confidence"],
    },
    {
        id: "spec-44",
        firstName: "Boris",
        lastName: "Novikov",
        phoneNumber: "+972540234567",
        photoUrl: null,
        birthDate: "1975-11-09T00:00:00.000Z",
        gender: "male",
        languages: ["ru", "uk", "en"],
        profession: "psychologist",
        meetingFormat: "online",
        experience: 22,
        pricePerSession: 295,
        services: ["Crisis intervention", "Suicide prevention", "Acute stress"],
    },
    {
        id: "spec-45",
        firstName: "Dina",
        lastName: "Rosen",
        phoneNumber: "+972541234568",
        photoUrl: null,
        birthDate: "1992-04-16T00:00:00.000Z",
        gender: "female",
        languages: ["he", "en"],
        profession: "therapist",
        meetingFormat: "offline",
        experience: 5,
        pricePerSession: 128,
        services: ["Art therapy", "Creative expression", "Trauma"],
    },
    {
        id: "spec-46",
        firstName: "Roman",
        lastName: "Tarasov",
        phoneNumber: "+972542234567",
        photoUrl: null,
        birthDate: "1986-09-02T00:00:00.000Z",
        gender: "male",
        languages: ["ru", "en"],
        profession: "coach",
        meetingFormat: "online",
        experience: 10,
        pricePerSession: 210,
        services: ["Executive coaching", "Team dynamics", "Conflict"],
    },
    {
        id: "spec-47",
        firstName: "Yulia",
        lastName: "Pavlova",
        phoneNumber: "+972543234567",
        photoUrl: null,
        birthDate: "1984-12-20T00:00:00.000Z",
        gender: "female",
        languages: ["ru", "he", "en"],
        profession: "psychologist",
        meetingFormat: "online",
        experience: 11,
        pricePerSession: 212,
        services: ["Pregnancy", "Fertility", "Parenthood"],
    },
    {
        id: "spec-48",
        firstName: "Amir",
        lastName: "Ben-Shalom",
        phoneNumber: "+972544234567",
        photoUrl: null,
        birthDate: "1981-03-07T00:00:00.000Z",
        gender: "male",
        languages: ["he", "en"],
        profession: "therapist",
        meetingFormat: "offline",
        experience: 14,
        pricePerSession: 258,
        services: ["Veterans", "PTSD", "Transition to civilian life"],
    },
    {
        id: "spec-49",
        firstName: "Irina",
        lastName: "Belova",
        phoneNumber: "+972545234567",
        photoUrl: null,
        birthDate: "1991-06-14T00:00:00.000Z",
        gender: "female",
        languages: ["ru", "uk", "en"],
        profession: "psychologist",
        meetingFormat: "online",
        experience: 6,
        pricePerSession: 144,
        services: ["Social anxiety", "Shyness", "Assertiveness"],
    },
    {
        id: "spec-50",
        firstName: "Ron",
        lastName: "Shapira",
        phoneNumber: "+972546234567",
        photoUrl: null,
        birthDate: "1989-08-28T00:00:00.000Z",
        gender: "male",
        languages: ["he", "en"],
        profession: "coach",
        meetingFormat: "online",
        experience: 9,
        pricePerSession: 175,
        services: ["Retirement planning", "Second career", "Purpose"],
    },
];
