import type {
    Degree,
    Profession,
    SpecialistDTO,
    WorkMethod,
} from "@/features/specialist/model/types";

type SpecialistMockBase = Omit<
    SpecialistDTO,
    "about" | "workMethods" | "mainDegree" | "additionalDegrees" | "values"
>;

const ABOUT_BY_PROFESSION: Record<Profession, string> = {
    psychologist:
        "Помогаю бережно пройти через кризисы, улучшить эмоциональное состояние и выстроить устойчивые стратегии самоподдержки.",
    therapist:
        "Работаю с тревогой, травматическим опытом и отношениями, создавая безопасное пространство для постепенных изменений.",
    coach:
        "Помогаю прояснить цели, выстроить реалистичный план действий и двигаться к результату без выгорания.",
};

const VALUES_BY_PROFESSION: Record<Profession, string> = {
    psychologist:
        "Бережность, конфиденциальность, уважение границ и фокус на устойчивых долгосрочных изменениях.",
    therapist:
        "Эмпатия, принятие, профессиональная этика и работа в темпе клиента.",
    coach: "Партнерство, ответственность, честная обратная связь и ориентация на практический результат.",
};

const WORK_METHODS_BY_PROFESSION: Record<Profession, WorkMethod[]> = {
    psychologist: ["CBT", "Schema Therapy", "Psychodynamic Therapy"],
    therapist: ["Gestalt Therapy", "Psychoanalysis", "Client-Centered Therapy"],
    coach: ["Coaching", "Positive Therapy", "Transactional Analysis"],
};

const MAIN_DEGREE_BY_PROFESSION: Record<Profession, Degree> = {
    psychologist: {
        degreeName: "Магистр психологии",
        description:
            "Базовое профильное образование по психологическому консультированию и психодиагностике.",
    },
    therapist: {
        degreeName: "Магистр клинической психологии",
        description:
            "Подготовка по психотерапевтической работе с эмоциональными и поведенческими трудностями.",
    },
    coach: {
        degreeName: "Сертифицированный коуч ICF",
        description:
            "Профессиональная подготовка по коучинговым инструментам и сопровождению изменений.",
    },
};

const ADDITIONAL_DEGREES_BY_PROFESSION: Record<Profession, Degree[]> = {
    psychologist: [
        {
            degreeName: "Повышение квалификации по CBT",
            description:
                "Практическая подготовка по когнитивно-поведенческим техникам.",
        },
    ],
    therapist: [
        {
            degreeName: "Специализация по травма-терапии",
            description:
                "Работа с последствиями травматического опыта и стабилизацией состояния.",
        },
    ],
    coach: [
        {
            degreeName: "Профессиональный коучинг команд",
            description:
                "Инструменты сопровождения личных и карьерных изменений.",
        },
    ],
};

const baseSpecialistData: SpecialistMockBase[] = [
    {
        id: "spec-1",
        firstName: "Maya",
        lastName: "Levi",
        phoneNumber: "+972501234567",
        photoUrl: null,
        birthDate: "2024-06-10T09:00:00.000Z",
        gender: "female",
        languages: ["he", "en"],
        profession: "psychologist",
        meetingFormat: "online",
        sessionTypes: ["individual", "couple", "child"],
        experience: 9,
        pricePerSession: 120,
        services: ["trevozhnost", "stress", "emotional-burnout", "apatia-ustalost", "perepady-nastroyeniya", "razdrazhitelnost-zlost", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "chuvstvo-viny-styda", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "otnosheniya-s-roditelyami", "vospitanie-detej"],
    },
    {
        id: "spec-2",
        firstName: "Alex",
        lastName: "Petrov",
        phoneNumber: "+972541234567",
        photoUrl: null,
        birthDate: "2024-06-10T09:00:00.000Z",
        gender: "male",
        languages: ["ru", "en"],
        profession: "therapist",
        meetingFormat: "online",
        sessionTypes: ["individual"],
        experience: 12,
        pricePerSession: 180,
        services: ["trevozhnost", "stress", "emotional-burnout", "apatia-ustalost", "perepady-nastroyeniya", "razdrazhitelnost-zlost", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "chuvstvo-viny-styda", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "trevozhnye-rasstrojstva", "panicheskie-ataki", "depressivnye-sostoyaniya", "sotsialnaya-trevozhnost", "ptsr", "emdr-travma"],
    },
    {
        id: "spec-3",
        firstName: "Nadia",
        lastName: "Koval",
        phoneNumber: "+972521234567",
        photoUrl: null,
        birthDate: "2024-06-10T09:00:00.000Z",
        gender: "female",
        languages: ["uk", "ru"],
        profession: "coach",
        meetingFormat: "offline",
        sessionTypes: ["individual","couple"],
        experience: 6,
        pricePerSession: 140,
        services: ["postanovka-tselej", "dostizhenie-tselej", "plan-dejstvij", "dolgosrochnoe-planirovanie", "tajm-menedzhment", "samodistsiplina", "prokrastinatsiya-kouching", "privychki-rutina", "kariernyj-rost", "smena-professii", "sobesedovaniya", "peregovory-zarplata", "adaptatsiya-novaya-rabota", "liderstvo", "upravlenie-komandoj", "delegirovanie", "prinyatie-reshenij", "biznes-kouching", "uverennost-kouching", "work-life-balance", "energiya-resursnost", "profilaktika-vygoraniya"],
    },
    {
        id: "spec-4",
        firstName: "Omar",
        lastName: "Hassan",
        phoneNumber: "+972531234567",
        photoUrl: null,
        birthDate: "2024-06-10T09:00:00.000Z",
        gender: "male",
        languages: ["ar", "en"],
        profession: "therapist",
        meetingFormat: "online",
        sessionTypes: ["individual", "couple"],
        experience: 10,
        pricePerSession: 200,
        services: ["problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "vospitanie-detej", "konflikty-v-seme", "trudnosti-s-podrostkom", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "trevozhnye-rasstrojstva", "panicheskie-ataki", "depressivnye-sostoyaniya", "sotsialnaya-trevozhnost", "ptsr", "posledstviya-nasiliya", "silnye-travmaticheskie-sobytiya", "emdr-travma", "supruzheskaya-terapiya", "semeynaya-terapiya", "seksualnye-trudnosti", "detskaya-psihoterapiya", "podrostkovaya-psihoterapiya", "cbt", "geshtalt", "psihoanaliz", "schema-terapiya", "emdr"],
    },
    {
        id: "spec-5",
        firstName: "Lina",
        lastName: "Cohen",
        phoneNumber: "+972551234567",
        photoUrl: null,
        birthDate: "2024-06-10T09:00:00.000Z",
        gender: "female",
        languages: ["he", "ru", "en"],
        profession: "psychologist",
        meetingFormat: "offline",
        sessionTypes: ["individual"],
        experience: 8,
        pricePerSession: 160,
        services: ["nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "chuvstvo-viny-styda", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "otnosheniya-s-roditelyami", "vospitanie-detej", "konflikty-v-seme", "trudnosti-s-podrostkom", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "prokrastinatsiya", "samoorganizatsiya", "navyazchivye-mysli", "psihosomatika"],
    },
    {
        id: "spec-6",
        firstName: "David",
        lastName: "Shapiro",
        phoneNumber: "+972502234567",
        photoUrl: null,
        birthDate: "1985-03-15T00:00:00.000Z",
        gender: "male",
        languages: ["he", "en"],
        profession: "psychologist",
        meetingFormat: "online",
        sessionTypes: ["individual"],
        experience: 11,
        pricePerSession: 220,
        services: ["trevozhnost", "stress", "emotional-burnout", "apatia-ustalost", "perepady-nastroyeniya", "razdrazhitelnost-zlost", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "chuvstvo-viny-styda", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "otnosheniya-s-roditelyami", "vospitanie-detej", "konflikty-v-seme", "trudnosti-s-podrostkom", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "prokrastinatsiya", "samoorganizatsiya", "navyazchivye-mysli", "psihosomatika"],
    },
    {
        id: "spec-7",
        firstName: "Elena",
        lastName: "Volkov",
        phoneNumber: "+972503234567",
        photoUrl: null,
        birthDate: "1990-07-22T00:00:00.000Z",
        gender: "female",
        languages: ["ru", "en"],
        profession: "therapist",
        meetingFormat: "offline",
        sessionTypes: ["individual"],
        experience: 7,
        pricePerSession: 150,
        services: ["trevozhnost", "stress", "emotional-burnout", "apatia-ustalost", "perepady-nastroyeniya", "razdrazhitelnost-zlost", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "chuvstvo-viny-styda", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "vospitanie-detej", "konflikty-v-seme", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "trevozhnye-rasstrojstva", "panicheskie-ataki", "depressivnye-sostoyaniya", "ptsr", "emdr-travma", "okr", "fobii"],
    },
    {
        id: "spec-8",
        firstName: "Yael",
        lastName: "Ben-David",
        phoneNumber: "+972504234567",
        photoUrl: null,
        birthDate: "1988-11-08T00:00:00.000Z",
        gender: "female",
        languages: ["he", "en", "ru"],
        profession: "psychologist",
        meetingFormat: "online",
        sessionTypes: ["individual"],
        experience: 14,
        pricePerSession: 260,
        services: ["trevozhnost", "stress", "emotional-burnout", "apatia-ustalost", "perepady-nastroyeniya", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "lichnye-granitsy", "sozavisimost", "otnosheniya-s-roditelyami", "vospitanie-detej", "konflikty-v-seme", "trudnosti-s-podrostkom", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "prokrastinatsiya", "samoorganizatsiya", "navyazchivye-mysli", "psihosomatika"],
    },
    {
        id: "spec-9",
        firstName: "Michael",
        lastName: "Rosenberg",
        phoneNumber: "+972505234567",
        photoUrl: null,
        birthDate: "1982-01-30T00:00:00.000Z",
        gender: "male",
        languages: ["he", "en"],
        profession: "coach",
        meetingFormat: "online",
        sessionTypes: ["individual"],
        experience: 5,
        pricePerSession: 130,
        services: ["postanovka-tselej", "dostizhenie-tselej", "plan-dejstvij", "dolgosrochnoe-planirovanie", "tajm-menedzhment", "samodistsiplina", "prokrastinatsiya-kouching", "privychki-rutina", "kariernyj-rost", "smena-professii", "sobesedovaniya", "peregovory-zarplata", "adaptatsiya-novaya-rabota", "liderstvo", "upravlenie-komandoj", "delegirovanie", "prinyatie-reshenij", "biznes-kouching", "finansovye-tseli", "strategiya-razvitiya", "lichnyj-brend", "uverennost-kouching", "publichnye-vystupleniya", "kommunikatsiya-soft-skills", "work-life-balance", "energiya-resursnost", "profilaktika-vygoraniya"],
    },
    {
        id: "spec-10",
        firstName: "Svetlana",
        lastName: "Kozlov",
        phoneNumber: "+972506234567",
        photoUrl: null,
        birthDate: "1979-09-12T00:00:00.000Z",
        gender: "female",
        languages: ["ru", "uk", "en"],
        profession: "therapist",
        meetingFormat: "offline",
        sessionTypes: ["individual", "couple", "child"],
        experience: 18,
        pricePerSession: 280,
        services: ["vospitanie-detej", "konflikty-v-seme", "trudnosti-s-podrostkom", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "trevozhnye-rasstrojstva", "panicheskie-ataki", "depressivnye-sostoyaniya", "sotsialnaya-trevozhnost", "ptsr", "posledstviya-nasiliya", "silnye-travmaticheskie-sobytiya", "emdr-travma", "okr", "fobii", "navyazchivye-sostoyaniya", "prl", "rasstrojstva-lichnosti", "emotsii-impulsivnost", "supruzheskaya-terapiya", "semeynaya-terapiya", "seksualnye-trudnosti", "detskaya-psihoterapiya", "podrostkovaya-psihoterapiya", "trudnosti-povedeniya-adaptatsii", "cbt", "geshtalt", "psihoanaliz", "schema-terapiya"],
    },
    {
        id: "spec-11",
        firstName: "Ahmad",
        lastName: "Khalil",
        phoneNumber: "+972507234567",
        photoUrl: null,
        birthDate: "1992-04-25T00:00:00.000Z",
        gender: "male",
        languages: ["ar", "he", "en"],
        profession: "psychologist",
        meetingFormat: "online",
        sessionTypes: ["individual"],
        experience: 6,
        pricePerSession: 145,
        services: ["stress", "emotional-burnout", "apatia-ustalost", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "otnosheniya-s-roditelyami", "vospitanie-detej", "konflikty-v-seme", "trudnosti-s-podrostkom", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "prokrastinatsiya", "samoorganizatsiya", "navyazchivye-mysli", "psihosomatika"],
    },
    {
        id: "spec-12",
        firstName: "Tamar",
        lastName: "Goldstein",
        phoneNumber: "+972508234567",
        photoUrl: null,
        birthDate: "1987-12-03T00:00:00.000Z",
        gender: "female",
        languages: ["he", "en"],
        profession: "psychologist",
        meetingFormat: "online",
        sessionTypes: ["individual"],
        experience: 9,
        pricePerSession: 190,
        services: ["trevozhnost", "stress", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "chuvstvo-viny-styda", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "otnosheniya-s-roditelyami", "vospitanie-detej", "konflikty-v-seme", "trudnosti-s-podrostkom", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "prokrastinatsiya", "samoorganizatsiya", "navyazchivye-mysli", "psihosomatika"],
    },
    {
        id: "spec-13",
        firstName: "Dmitry",
        lastName: "Sokolov",
        phoneNumber: "+972509234567",
        photoUrl: null,
        birthDate: "1984-06-18T00:00:00.000Z",
        gender: "male",
        languages: ["ru", "en"],
        profession: "coach",
        meetingFormat: "offline",
        sessionTypes: ["individual"],
        experience: 8,
        pricePerSession: 165,
        services: ["postanovka-tselej", "dostizhenie-tselej", "plan-dejstvij", "dolgosrochnoe-planirovanie", "tajm-menedzhment", "samodistsiplina", "prokrastinatsiya-kouching", "privychki-rutina", "kariernyj-rost", "smena-professii", "sobesedovaniya", "peregovory-zarplata", "adaptatsiya-novaya-rabota", "liderstvo", "upravlenie-komandoj", "delegirovanie", "prinyatie-reshenij", "biznes-kouching", "finansovye-tseli", "strategiya-razvitiya", "lichnyj-brend", "uverennost-kouching", "publichnye-vystupleniya", "kommunikatsiya-soft-skills", "lichnye-granitsy-obschenie", "work-life-balance", "energiya-resursnost", "profilaktika-vygoraniya"],
    },
    {
        id: "spec-14",
        firstName: "Rachel",
        lastName: "Levy",
        phoneNumber: "+972510234567",
        photoUrl: null,
        birthDate: "1991-02-14T00:00:00.000Z",
        gender: "female",
        languages: ["he", "en", "ru"],
        profession: "therapist",
        meetingFormat: "online",
        sessionTypes: ["individual"],
        experience: 4,
        pricePerSession: 110,
        services: ["trevozhnye-rasstrojstva", "panicheskie-ataki", "depressivnye-sostoyaniya", "sotsialnaya-trevozhnost", "ptsr", "posledstviya-nasiliya", "silnye-travmaticheskie-sobytiya", "emdr-travma", "okr", "fobii", "navyazchivye-sostoyaniya", "prl", "rasstrojstva-lichnosti", "emotsii-impulsivnost", "rpp", "kompulsivnoe-pereedanie", "kontrol-vesa", "supruzheskaya-terapiya", "semeynaya-terapiya", "seksualnye-trudnosti", "detskaya-psihoterapiya", "podrostkovaya-psihoterapiya", "trudnosti-povedeniya-adaptatsii", "cbt", "geshtalt", "psihoanaliz", "schema-terapiya", "emdr"],
    },
    {
        id: "spec-15",
        firstName: "Igor",
        lastName: "Petrenko",
        phoneNumber: "+972511234567",
        photoUrl: null,
        birthDate: "1976-08-07T00:00:00.000Z",
        gender: "male",
        languages: ["uk", "ru", "en"],
        profession: "psychologist",
        meetingFormat: "offline",
        sessionTypes: ["individual"],
        experience: 20,
        pricePerSession: 300,
        services: ["trevozhnost", "stress", "emotional-burnout", "apatia-ustalost", "perepady-nastroyeniya", "razdrazhitelnost-zlost", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "chuvstvo-viny-styda", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "otnosheniya-s-roditelyami", "vospitanie-detej", "konflikty-v-seme", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "prokrastinatsiya", "samoorganizatsiya", "navyazchivye-mysli", "psihosomatika"],
    },
    {
        id: "spec-16",
        firstName: "Noa",
        lastName: "Friedman",
        phoneNumber: "+972512234567",
        photoUrl: null,
        birthDate: "1993-05-20T00:00:00.000Z",
        gender: "female",
        languages: ["he", "en"],
        profession: "coach",
        meetingFormat: "online",
        sessionTypes: ["individual"],
        experience: 3,
        pricePerSession: 100,
        services: ["postanovka-tselej", "dostizhenie-tselej", "plan-dejstvij", "tajm-menedzhment", "samodistsiplina", "prokrastinatsiya-kouching", "privychki-rutina", "kariernyj-rost", "smena-professii", "sobesedovaniya", "peregovory-zarplata", "adaptatsiya-novaya-rabota", "liderstvo", "upravlenie-komandoj", "delegirovanie", "prinyatie-reshenij", "biznes-kouching", "finansovye-tseli", "strategiya-razvitiya", "work-life-balance", "energiya-resursnost", "profilaktika-vygoraniya"],
    },
    {
        id: "spec-17",
        firstName: "Viktor",
        lastName: "Orlov",
        phoneNumber: "+972513234567",
        photoUrl: null,
        birthDate: "1980-10-11T00:00:00.000Z",
        gender: "male",
        languages: ["ru", "en"],
        profession: "therapist",
        meetingFormat: "online",
        sessionTypes: ["individual"],
        experience: 13,
        pricePerSession: 240,
        services: ["trevozhnost", "stress", "emotional-burnout", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "vospitanie-detej", "konflikty-v-seme", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "trevozhnye-rasstrojstva", "panicheskie-ataki", "depressivnye-sostoyaniya", "sotsialnaya-trevozhnost", "ptsr", "emdr-travma", "okr", "fobii", "prl", "rasstrojstva-lichnosti", "supruzheskaya-terapiya", "semeynaya-terapiya", "seksualnye-trudnosti"],
    },
    {
        id: "spec-18",
        firstName: "Hannah",
        lastName: "Weiss",
        phoneNumber: "+972514234567",
        photoUrl: null,
        birthDate: "1989-03-28T00:00:00.000Z",
        gender: "female",
        languages: ["he", "en", "ar"],
        profession: "psychologist",
        meetingFormat: "offline",
        sessionTypes: ["individual", "child", "teen"],
        experience: 10,
        pricePerSession: 205,
        services: ["trevozhnost", "stress", "emotional-burnout", "apatia-ustalost", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "odinochestvo", "lichnye-granitsy", "otnosheniya-s-roditelyami", "vospitanie-detej", "konflikty-v-seme", "trudnosti-s-podrostkom", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "prokrastinatsiya", "samoorganizatsiya", "navyazchivye-mysli", "psihosomatika"],
    },
    {
        id: "spec-19",
        firstName: "Sergey",
        lastName: "Ivanov",
        phoneNumber: "+972515234567",
        photoUrl: null,
        birthDate: "1983-07-05T00:00:00.000Z",
        gender: "male",
        languages: ["ru", "uk", "en"],
        profession: "coach",
        meetingFormat: "offline",
        sessionTypes: ["individual"],
        experience: 6,
        pricePerSession: 142,
        services: ["postanovka-tselej", "dostizhenie-tselej", "plan-dejstvij", "dolgosrochnoe-planirovanie", "tajm-menedzhment", "kariernyj-rost", "smena-professii", "sobesedovaniya", "peregovory-zarplata", "adaptatsiya-novaya-rabota", "liderstvo", "upravlenie-komandoj", "delegirovanie", "prinyatie-reshenij", "biznes-kouching", "finansovye-tseli", "strategiya-razvitiya", "lichnyj-brend", "uverennost-kouching", "publichnye-vystupleniya", "kommunikatsiya-soft-skills", "lichnye-granitsy-obschenie", "work-life-balance", "energiya-resursnost", "profilaktika-vygoraniya"],
    },
    {
        id: "spec-20",
        firstName: "Miriam",
        lastName: "Cohen",
        phoneNumber: "+972516234567",
        photoUrl: null,
        birthDate: "1978-11-19T00:00:00.000Z",
        gender: "female",
        languages: ["he", "en"],
        profession: "therapist",
        meetingFormat: "online",
        sessionTypes: ["individual"],
        experience: 16,
        pricePerSession: 270,
        services: ["poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "trevozhnye-rasstrojstva", "panicheskie-ataki", "depressivnye-sostoyaniya", "sotsialnaya-trevozhnost", "ptsr", "posledstviya-nasiliya", "silnye-travmaticheskie-sobytiya", "emdr-travma", "okr", "fobii", "navyazchivye-sostoyaniya", "prl", "rasstrojstva-lichnosti", "emotsii-impulsivnost", "rpp", "kompulsivnoe-pereedanie", "kontrol-vesa", "supruzheskaya-terapiya", "semeynaya-terapiya", "seksualnye-trudnosti", "detskaya-psihoterapiya", "podrostkovaya-psihoterapiya", "trudnosti-povedeniya-adaptatsii", "cbt", "geshtalt", "psihoanaliz", "schema-terapiya"],
    },
    {
        id: "spec-21",
        firstName: "Andrey",
        lastName: "Morozov",
        phoneNumber: "+972517234567",
        photoUrl: null,
        birthDate: "1994-01-09T00:00:00.000Z",
        gender: "male",
        languages: ["ru", "en"],
        profession: "psychologist",
        meetingFormat: "online",
        sessionTypes: ["individual", "teen"],
        experience: 4,
        pricePerSession: 115,
        services: ["trevozhnost", "stress", "emotional-burnout", "apatia-ustalost", "perepady-nastroyeniya", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "chuvstvo-viny-styda", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "otnosheniya-s-roditelyami", "vospitanie-detej", "konflikty-v-seme", "trudnosti-s-podrostkom", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "prokrastinatsiya", "samoorganizatsiya", "navyazchivye-mysli", "psihosomatika"],
    },
    {
        id: "spec-22",
        firstName: "Sarah",
        lastName: "Mizrahi",
        phoneNumber: "+972518234567",
        photoUrl: null,
        birthDate: "1986-04-16T00:00:00.000Z",
        gender: "female",
        languages: ["he", "en", "ru"],
        profession: "psychologist",
        meetingFormat: "offline",
        sessionTypes: ["individual", "couple", "child"],
        experience: 12,
        pricePerSession: 225,
        services: ["trevozhnost", "stress", "emotional-burnout", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "otnosheniya-s-roditelyami", "vospitanie-detej", "konflikty-v-seme", "trudnosti-s-podrostkom", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "prokrastinatsiya", "samoorganizatsiya", "navyazchivye-mysli", "psihosomatika"],
    },
    {
        id: "spec-23",
        firstName: "Oleg",
        lastName: "Kuznetsov",
        phoneNumber: "+972519234567",
        photoUrl: null,
        birthDate: "1981-12-22T00:00:00.000Z",
        gender: "male",
        languages: ["ru", "uk", "en"],
        profession: "therapist",
        meetingFormat: "online",
        sessionTypes: ["individual"],
        experience: 11,
        pricePerSession: 215,
        services: ["trevozhnost", "stress", "emotional-burnout", "apatia-ustalost", "perepady-nastroyeniya", "razdrazhitelnost-zlost", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "chuvstvo-viny-styda", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "vospitanie-detej", "konflikty-v-seme", "trudnosti-s-podrostkom", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "trevozhnye-rasstrojstva", "panicheskie-ataki", "depressivnye-sostoyaniya", "ptsr", "emdr-travma", "geshtalt"],
    },
    {
        id: "spec-24",
        firstName: "Leah",
        lastName: "Berger",
        phoneNumber: "+972520234567",
        photoUrl: null,
        birthDate: "1990-06-30T00:00:00.000Z",
        gender: "female",
        languages: ["he", "en"],
        profession: "coach",
        meetingFormat: "online",
        sessionTypes: ["individual"],
        experience: 7,
        pricePerSession: 155,
        services: ["postanovka-tselej", "dostizhenie-tselej", "plan-dejstvij", "dolgosrochnoe-planirovanie", "tajm-menedzhment", "samodistsiplina", "prokrastinatsiya-kouching", "privychki-rutina", "kariernyj-rost", "smena-professii", "sobesedovaniya", "peregovory-zarplata", "adaptatsiya-novaya-rabota", "liderstvo", "upravlenie-komandoj", "delegirovanie", "prinyatie-reshenij", "biznes-kouching", "finansovye-tseli", "strategiya-razvitiya", "lichnyj-brend", "uverennost-kouching", "publichnye-vystupleniya", "kommunikatsiya-soft-skills", "lichnye-granitsy-obschenie", "work-life-balance", "energiya-resursnost", "profilaktika-vygoraniya"],
    },
    {
        id: "spec-25",
        firstName: "Rami",
        lastName: "Elkabetz",
        phoneNumber: "+972521234567",
        photoUrl: null,
        birthDate: "1985-09-14T00:00:00.000Z",
        gender: "male",
        languages: ["he", "ar", "en"],
        profession: "psychologist",
        meetingFormat: "offline",
        sessionTypes: ["individual"],
        experience: 9,
        pricePerSession: 185,
        services: ["trevozhnost", "stress", "emotional-burnout", "apatia-ustalost", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "chuvstvo-viny-styda", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "otnosheniya-s-roditelyami", "vospitanie-detej", "konflikty-v-seme", "trudnosti-s-podrostkom", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "prokrastinatsiya", "samoorganizatsiya", "navyazchivye-mysli", "psihosomatika"],
    },
    {
        id: "spec-26",
        firstName: "Olga",
        lastName: "Romanova",
        phoneNumber: "+972522234567",
        photoUrl: null,
        birthDate: "1987-02-28T00:00:00.000Z",
        gender: "female",
        languages: ["ru", "en"],
        profession: "therapist",
        meetingFormat: "offline",
        sessionTypes: ["individual"],
        experience: 8,
        pricePerSession: 170,
        services: ["trevozhnost", "stress", "emotional-burnout", "apatia-ustalost", "perepady-nastroyeniya", "razdrazhitelnost-zlost", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "chuvstvo-viny-styda", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "otnosheniya-s-roditelyami", "vospitanie-detej", "konflikty-v-seme", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "trevozhnye-rasstrojstva", "panicheskie-ataki", "depressivnye-sostoyaniya", "sotsialnaya-trevozhnost", "ptsr", "emdr-travma"],
    },
    {
        id: "spec-27",
        firstName: "Jonathan",
        lastName: "Stern",
        phoneNumber: "+972523234567",
        photoUrl: null,
        birthDate: "1979-08-03T00:00:00.000Z",
        gender: "male",
        languages: ["he", "en"],
        profession: "psychologist",
        meetingFormat: "online",
        sessionTypes: ["individual"],
        experience: 15,
        pricePerSession: 265,
        services: ["trevozhnost", "stress", "emotional-burnout", "apatia-ustalost", "perepady-nastroyeniya", "razdrazhitelnost-zlost", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "chuvstvo-viny-styda", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "otnosheniya-s-roditelyami", "vospitanie-detej", "konflikty-v-seme", "trudnosti-s-podrostkom", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "prokrastinatsiya", "samoorganizatsiya", "navyazchivye-mysli", "psihosomatika"],
    },
    {
        id: "spec-28",
        firstName: "Kateryna",
        lastName: "Shevchenko",
        phoneNumber: "+972524234567",
        photoUrl: null,
        birthDate: "1992-10-17T00:00:00.000Z",
        gender: "female",
        languages: ["uk", "ru", "en"],
        profession: "coach",
        meetingFormat: "online",
        sessionTypes: ["individual"],
        experience: 5,
        pricePerSession: 135,
        services: ["postanovka-tselej", "dostizhenie-tselej", "plan-dejstvij", "dolgosrochnoe-planirovanie", "tajm-menedzhment", "samodistsiplina", "prokrastinatsiya-kouching", "privychki-rutina", "kariernyj-rost", "smena-professii", "sobesedovaniya", "peregovory-zarplata", "adaptatsiya-novaya-rabota", "liderstvo", "upravlenie-komandoj", "delegirovanie", "prinyatie-reshenij", "biznes-kouching", "finansovye-tseli", "strategiya-razvitiya", "lichnyj-brend", "uverennost-kouching", "publichnye-vystupleniya", "kommunikatsiya-soft-skills", "work-life-balance", "energiya-resursnost", "profilaktika-vygoraniya"],
    },
    {
        id: "spec-29",
        firstName: "Youssef",
        lastName: "Nassar",
        phoneNumber: "+972525234567",
        photoUrl: null,
        birthDate: "1984-05-24T00:00:00.000Z",
        gender: "male",
        languages: ["ar", "he", "en"],
        profession: "therapist",
        meetingFormat: "offline",
        sessionTypes: ["individual"],
        experience: 10,
        pricePerSession: 195,
        services: ["trevozhnost", "stress", "emotional-burnout", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "otnosheniya-s-roditelyami", "vospitanie-detej", "konflikty-v-seme", "trudnosti-s-podrostkom", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "trevozhnye-rasstrojstva", "panicheskie-ataki", "depressivnye-sostoyaniya", "sotsialnaya-trevozhnost", "ptsr", "posledstviya-nasiliya", "silnye-travmaticheskie-sobytiya", "emdr-travma", "supruzheskaya-terapiya", "semeynaya-terapiya", "seksualnye-trudnosti"],
    },
    {
        id: "spec-30",
        firstName: "Rivka",
        lastName: "Adler",
        phoneNumber: "+972526234567",
        photoUrl: null,
        birthDate: "1986-01-12T00:00:00.000Z",
        gender: "female",
        languages: ["he", "en"],
        profession: "psychologist",
        meetingFormat: "online",
        sessionTypes: ["individual"],
        experience: 11,
        pricePerSession: 218,
        services: ["trevozhnost", "stress", "emotional-burnout", "apatia-ustalost", "perepady-nastroyeniya", "razdrazhitelnost-zlost", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "chuvstvo-viny-styda", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "otnosheniya-s-roditelyami", "vospitanie-detej", "konflikty-v-seme", "trudnosti-s-podrostkom", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "prokrastinatsiya", "samoorganizatsiya", "navyazchivye-mysli", "psihosomatika"],
    },
    {
        id: "spec-31",
        firstName: "Pavel",
        lastName: "Volkov",
        phoneNumber: "+972527234567",
        photoUrl: null,
        birthDate: "1991-07-08T00:00:00.000Z",
        gender: "male",
        languages: ["ru", "en"],
        profession: "coach",
        meetingFormat: "offline",
        sessionTypes: ["individual"],
        experience: 4,
        pricePerSession: 112,
        services: ["postanovka-tselej", "dostizhenie-tselej", "plan-dejstvij", "dolgosrochnoe-planirovanie", "tajm-menedzhment", "samodistsiplina", "prokrastinatsiya-kouching", "privychki-rutina", "kariernyj-rost", "smena-professii", "sobesedovaniya", "peregovory-zarplata", "adaptatsiya-novaya-rabota", "liderstvo", "upravlenie-komandoj", "delegirovanie", "prinyatie-reshenij", "biznes-kouching", "finansovye-tseli", "strategiya-razvitiya", "lichnyj-brend", "uverennost-kouching", "publichnye-vystupleniya", "kommunikatsiya-soft-skills", "lichnye-granitsy-obschenie", "work-life-balance", "energiya-resursnost", "profilaktika-vygoraniya"],
    },
    {
        id: "spec-32",
        firstName: "Anna",
        lastName: "Smirnova",
        phoneNumber: "+972528234567",
        photoUrl: null,
        birthDate: "1988-11-25T00:00:00.000Z",
        gender: "female",
        languages: ["ru", "he", "en"],
        profession: "therapist",
        meetingFormat: "online",
        sessionTypes: ["individual"],
        experience: 9,
        pricePerSession: 188,
        services: ["trevozhnost", "stress", "emotional-burnout", "apatia-ustalost", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "chuvstvo-viny-styda", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "trevozhnye-rasstrojstva", "panicheskie-ataki", "depressivnye-sostoyaniya", "sotsialnaya-trevozhnost", "ptsr", "posledstviya-nasiliya", "silnye-travmaticheskie-sobytiya", "emdr-travma", "okr", "fobii", "prl", "rasstrojstva-lichnosti", "emotsii-impulsivnost", "supruzheskaya-terapiya", "semeynaya-terapiya"],
    },
    {
        id: "spec-33",
        firstName: "Daniel",
        lastName: "Katz",
        phoneNumber: "+972529234567",
        photoUrl: null,
        birthDate: "1982-04-02T00:00:00.000Z",
        gender: "male",
        languages: ["he", "en"],
        profession: "psychologist",
        meetingFormat: "offline",
        sessionTypes: ["individual"],
        experience: 14,
        pricePerSession: 255,
        services: ["trevozhnost", "stress", "emotional-burnout", "apatia-ustalost", "perepady-nastroyeniya", "razdrazhitelnost-zlost", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "chuvstvo-viny-styda", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "otnosheniya-s-roditelyami", "vospitanie-detej", "konflikty-v-seme", "trudnosti-s-podrostkom", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "prokrastinatsiya", "samoorganizatsiya", "navyazchivye-mysli", "psihosomatika"],
    },
    {
        id: "spec-34",
        firstName: "Marina",
        lastName: "Kravchenko",
        phoneNumber: "+972530234567",
        photoUrl: null,
        birthDate: "1993-09-19T00:00:00.000Z",
        gender: "female",
        languages: ["uk", "ru", "en"],
        profession: "psychologist",
        meetingFormat: "online",
        sessionTypes: ["individual"],
        experience: 6,
        pricePerSession: 148,
        services: ["trevozhnost", "stress", "emotional-burnout", "apatia-ustalost", "perepady-nastroyeniya", "razdrazhitelnost-zlost", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "chuvstvo-viny-styda", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "otnosheniya-s-roditelyami", "vospitanie-detej", "konflikty-v-seme", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "prokrastinatsiya", "samoorganizatsiya", "navyazchivye-mysli", "psihosomatika"],
    },
    {
        id: "spec-35",
        firstName: "Eitan",
        lastName: "Barak",
        phoneNumber: "+972531234567",
        photoUrl: null,
        birthDate: "1977-12-06T00:00:00.000Z",
        gender: "male",
        languages: ["he", "en"],
        profession: "therapist",
        meetingFormat: "online",
        sessionTypes: ["individual", "couple"],
        experience: 19,
        pricePerSession: 290,
        services: ["problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "vospitanie-detej", "konflikty-v-seme", "trudnosti-s-podrostkom", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "trevozhnye-rasstrojstva", "panicheskie-ataki", "depressivnye-sostoyaniya", "sotsialnaya-trevozhnost", "ptsr", "posledstviya-nasiliya", "silnye-travmaticheskie-sobytiya", "emdr-travma", "okr", "fobii", "navyazchivye-sostoyaniya", "prl", "rasstrojstva-lichnosti", "emotsii-impulsivnost", "rpp", "kompulsivnoe-pereedanie", "kontrol-vesa", "supruzheskaya-terapiya", "semeynaya-terapiya", "seksualnye-trudnosti"],
    },
    {
        id: "spec-36",
        firstName: "Inna",
        lastName: "Bondarenko",
        phoneNumber: "+972532234567",
        photoUrl: null,
        birthDate: "1989-03-11T00:00:00.000Z",
        gender: "female",
        languages: ["uk", "ru", "en"],
        profession: "coach",
        meetingFormat: "offline",
        sessionTypes: ["individual"],
        experience: 8,
        pricePerSession: 168,
        services: ["postanovka-tselej", "dostizhenie-tselej", "plan-dejstvij", "dolgosrochnoe-planirovanie", "tajm-menedzhment", "samodistsiplina", "prokrastinatsiya-kouching", "privychki-rutina", "kariernyj-rost", "smena-professii", "sobesedovaniya", "peregovory-zarplata", "adaptatsiya-novaya-rabota", "liderstvo", "upravlenie-komandoj", "delegirovanie", "prinyatie-reshenij", "biznes-kouching", "finansovye-tseli", "strategiya-razvitiya", "lichnyj-brend", "uverennost-kouching", "publichnye-vystupleniya", "kommunikatsiya-soft-skills", "work-life-balance", "energiya-resursnost", "profilaktika-vygoraniya"],
    },
    {
        id: "spec-37",
        firstName: "Moshe",
        lastName: "Golan",
        phoneNumber: "+972533234567",
        photoUrl: null,
        birthDate: "1980-06-27T00:00:00.000Z",
        gender: "male",
        languages: ["he", "en", "ru"],
        profession: "psychologist",
        meetingFormat: "offline",
        sessionTypes: ["individual"],
        experience: 13,
        pricePerSession: 245,
        services: ["trevozhnost", "stress", "emotional-burnout", "apatia-ustalost", "perepady-nastroyeniya", "razdrazhitelnost-zlost", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "chuvstvo-viny-styda", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "otnosheniya-s-roditelyami", "vospitanie-detej", "konflikty-v-seme", "trudnosti-s-podrostkom", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "prokrastinatsiya", "samoorganizatsiya", "navyazchivye-mysli", "psihosomatika"],
    },
    {
        id: "spec-38",
        firstName: "Valentina",
        lastName: "Fedorova",
        phoneNumber: "+972534234567",
        photoUrl: null,
        birthDate: "1985-02-14T00:00:00.000Z",
        gender: "female",
        languages: ["ru", "en"],
        profession: "therapist",
        meetingFormat: "online",
        sessionTypes: ["individual"],
        experience: 10,
        pricePerSession: 198,
        services: ["trevozhnost", "stress", "emotional-burnout", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "chuvstvo-viny-styda", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "vospitanie-detej", "konflikty-v-seme", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "trevozhnye-rasstrojstva", "panicheskie-ataki", "depressivnye-sostoyaniya", "ptsr", "emdr-travma", "okr", "fobii", "prl", "rasstrojstva-lichnosti", "emotsii-impulsivnost", "schema-terapiya"],
    },
    {
        id: "spec-39",
        firstName: "Guy",
        lastName: "Peretz",
        phoneNumber: "+972535234567",
        photoUrl: null,
        birthDate: "1994-08-21T00:00:00.000Z",
        gender: "male",
        languages: ["he", "en"],
        profession: "coach",
        meetingFormat: "online",
        sessionTypes: ["individual"],
        experience: 3,
        pricePerSession: 105,
        services: ["postanovka-tselej", "dostizhenie-tselej", "plan-dejstvij", "dolgosrochnoe-planirovanie", "tajm-menedzhment", "samodistsiplina", "kariernyj-rost", "smena-professii", "sobesedovaniya", "peregovory-zarplata", "adaptatsiya-novaya-rabota", "liderstvo", "upravlenie-komandoj", "delegirovanie", "prinyatie-reshenij", "biznes-kouching", "finansovye-tseli", "strategiya-razvitiya", "lichnyj-brend", "uverennost-kouching", "publichnye-vystupleniya", "kommunikatsiya-soft-skills", "lichnye-granitsy-obschenie", "work-life-balance", "energiya-resursnost", "profilaktika-vygoraniya"],
    },
    {
        id: "spec-40",
        firstName: "Natalia",
        lastName: "Sidorova",
        phoneNumber: "+972536234567",
        photoUrl: null,
        birthDate: "1983-10-05T00:00:00.000Z",
        gender: "female",
        languages: ["ru", "uk", "en"],
        profession: "psychologist",
        meetingFormat: "offline",
        sessionTypes: ["individual"],
        experience: 12,
        pricePerSession: 230,
        services: ["trevozhnost", "stress", "emotional-burnout", "apatia-ustalost", "perepady-nastroyeniya", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "chuvstvo-viny-styda", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "otnosheniya-s-roditelyami", "vospitanie-detej", "konflikty-v-seme", "trudnosti-s-podrostkom", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "prokrastinatsiya", "samoorganizatsiya", "navyazchivye-mysli", "psihosomatika"],
    },
    {
        id: "spec-41",
        firstName: "Tal",
        lastName: "Avraham",
        phoneNumber: "+972537234567",
        photoUrl: null,
        birthDate: "1990-05-18T00:00:00.000Z",
        gender: "female",
        languages: ["he", "en"],
        profession: "psychologist",
        meetingFormat: "online",
        sessionTypes: ["individual"],
        experience: 7,
        pricePerSession: 158,
        services: ["trevozhnost", "stress", "emotional-burnout", "apatia-ustalost", "perepady-nastroyeniya", "razdrazhitelnost-zlost", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "chuvstvo-viny-styda", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "otnosheniya-s-roditelyami", "vospitanie-detej", "konflikty-v-seme", "trudnosti-s-podrostkom", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "prokrastinatsiya", "samoorganizatsiya", "navyazchivye-mysli", "psihosomatika"],
    },
    {
        id: "spec-42",
        firstName: "Maxim",
        lastName: "Popov",
        phoneNumber: "+972538234567",
        photoUrl: null,
        birthDate: "1987-01-23T00:00:00.000Z",
        gender: "male",
        languages: ["ru", "en"],
        profession: "therapist",
        meetingFormat: "offline",
        sessionTypes: ["individual"],
        experience: 9,
        pricePerSession: 182,
        services: ["trevozhnost", "stress", "emotional-burnout", "apatia-ustalost", "perepady-nastroyeniya", "razdrazhitelnost-zlost", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "chuvstvo-viny-styda", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "prokrastinatsiya", "samoorganizatsiya", "navyazchivye-mysli", "psihosomatika", "trevozhnye-rasstrojstva", "panicheskie-ataki", "depressivnye-sostoyaniya", "sotsialnaya-trevozhnost", "ptsr", "emdr-travma", "okr", "fobii"],
    },
    {
        id: "spec-43",
        firstName: "Shira",
        lastName: "Dahan",
        phoneNumber: "+972539234567",
        photoUrl: null,
        birthDate: "1988-07-30T00:00:00.000Z",
        gender: "female",
        languages: ["he", "en", "ar"],
        profession: "coach",
        meetingFormat: "online",
        sessionTypes: ["individual"],
        experience: 6,
        pricePerSession: 138,
        services: ["postanovka-tselej", "dostizhenie-tselej", "plan-dejstvij", "dolgosrochnoe-planirovanie", "tajm-menedzhment", "samodistsiplina", "prokrastinatsiya-kouching", "privychki-rutina", "kariernyj-rost", "smena-professii", "sobesedovaniya", "peregovory-zarplata", "adaptatsiya-novaya-rabota", "liderstvo", "upravlenie-komandoj", "delegirovanie", "prinyatie-reshenij", "biznes-kouching", "finansovye-tseli", "strategiya-razvitiya", "lichnyj-brend", "uverennost-kouching", "publichnye-vystupleniya", "kommunikatsiya-soft-skills", "lichnye-granitsy-obschenie", "work-life-balance", "energiya-resursnost", "profilaktika-vygoraniya"],
    },
    {
        id: "spec-44",
        firstName: "Boris",
        lastName: "Novikov",
        phoneNumber: "+972540234567",
        photoUrl: null,
        birthDate: "1975-11-09T00:00:00.000Z",
        gender: "male",
        languages: ["ru", "uk", "en"],
        profession: "psychologist",
        meetingFormat: "online",
        sessionTypes: ["individual"],
        experience: 22,
        pricePerSession: 295,
        services: ["trevozhnost", "stress", "emotional-burnout", "apatia-ustalost", "perepady-nastroyeniya", "razdrazhitelnost-zlost", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "chuvstvo-viny-styda", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "otnosheniya-s-roditelyami", "vospitanie-detej", "konflikty-v-seme", "trudnosti-s-podrostkom", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "prokrastinatsiya", "samoorganizatsiya", "navyazchivye-mysli", "psihosomatika"],
    },
    {
        id: "spec-45",
        firstName: "Dina",
        lastName: "Rosen",
        phoneNumber: "+972541234568",
        photoUrl: null,
        birthDate: "1992-04-16T00:00:00.000Z",
        gender: "female",
        languages: ["he", "en"],
        profession: "therapist",
        meetingFormat: "offline",
        sessionTypes: ["individual"],
        experience: 5,
        pricePerSession: 128,
        services: ["poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "trevozhnye-rasstrojstva", "panicheskie-ataki", "depressivnye-sostoyaniya", "sotsialnaya-trevozhnost", "ptsr", "posledstviya-nasiliya", "silnye-travmaticheskie-sobytiya", "emdr-travma", "okr", "fobii", "navyazchivye-sostoyaniya", "prl", "rasstrojstva-lichnosti", "emotsii-impulsivnost", "rpp", "kompulsivnoe-pereedanie", "kontrol-vesa", "supruzheskaya-terapiya", "semeynaya-terapiya", "seksualnye-trudnosti", "detskaya-psihoterapiya", "podrostkovaya-psihoterapiya", "trudnosti-povedeniya-adaptatsii", "cbt", "geshtalt", "psihoanaliz", "schema-terapiya", "emdr"],
    },
    {
        id: "spec-46",
        firstName: "Roman",
        lastName: "Tarasov",
        phoneNumber: "+972542234567",
        photoUrl: null,
        birthDate: "1986-09-02T00:00:00.000Z",
        gender: "male",
        languages: ["ru", "en"],
        profession: "coach",
        meetingFormat: "online",
        sessionTypes: ["individual"],
        experience: 10,
        pricePerSession: 210,
        services: ["postanovka-tselej", "dostizhenie-tselej", "plan-dejstvij", "dolgosrochnoe-planirovanie", "tajm-menedzhment", "samodistsiplina", "prokrastinatsiya-kouching", "privychki-rutina", "kariernyj-rost", "smena-professii", "sobesedovaniya", "peregovory-zarplata", "adaptatsiya-novaya-rabota", "liderstvo", "upravlenie-komandoj", "delegirovanie", "prinyatie-reshenij", "biznes-kouching", "finansovye-tseli", "strategiya-razvitiya", "lichnyj-brend", "uverennost-kouching", "publichnye-vystupleniya", "kommunikatsiya-soft-skills", "work-life-balance", "energiya-resursnost", "profilaktika-vygoraniya"],
    },
    {
        id: "spec-47",
        firstName: "Yulia",
        lastName: "Pavlova",
        phoneNumber: "+972543234567",
        photoUrl: null,
        birthDate: "1984-12-20T00:00:00.000Z",
        gender: "female",
        languages: ["ru", "he", "en"],
        profession: "psychologist",
        meetingFormat: "online",
        sessionTypes: ["individual", "couple", "child"],
        experience: 11,
        pricePerSession: 212,
        services: ["trevozhnost", "stress", "emotional-burnout", "apatia-ustalost", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "otnosheniya-s-roditelyami", "vospitanie-detej", "konflikty-v-seme", "trudnosti-s-podrostkom", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "prokrastinatsiya", "samoorganizatsiya", "navyazchivye-mysli", "psihosomatika"],
    },
    {
        id: "spec-48",
        firstName: "Amir",
        lastName: "Ben-Shalom",
        phoneNumber: "+972544234567",
        photoUrl: null,
        birthDate: "1981-03-07T00:00:00.000Z",
        gender: "male",
        languages: ["he", "en"],
        profession: "therapist",
        meetingFormat: "offline",
        sessionTypes: ["individual"],
        experience: 14,
        pricePerSession: 258,
        services: ["trevozhnost", "stress", "emotional-burnout", "apatia-ustalost", "perepady-nastroyeniya", "razdrazhitelnost-zlost", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "chuvstvo-viny-styda", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "vospitanie-detej", "konflikty-v-seme", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "trevozhnye-rasstrojstva", "panicheskie-ataki", "depressivnye-sostoyaniya", "ptsr", "emdr-travma", "sotsialnaya-trevozhnost", "geshtalt"],
    },
    {
        id: "spec-49",
        firstName: "Irina",
        lastName: "Belova",
        phoneNumber: "+972545234567",
        photoUrl: null,
        birthDate: "1991-06-14T00:00:00.000Z",
        gender: "female",
        languages: ["ru", "uk", "en"],
        profession: "psychologist",
        meetingFormat: "online",
        sessionTypes: ["individual"],
        experience: 6,
        pricePerSession: 144,
        services: ["trevozhnost", "stress", "emotional-burnout", "apatia-ustalost", "perepady-nastroyeniya", "razdrazhitelnost-zlost", "nizkaya-samoocenka", "neuverennost-v-sebe", "samoprinyatie", "chuvstvo-viny-styda", "samoopredelenie", "vozrastnye-krizisy", "problemy-v-otnosheniyah", "konflikty-v-pare", "razvod-rasstavanie", "odinochestvo", "lichnye-granitsy", "sozavisimost", "otnosheniya-s-roditelyami", "vospitanie-detej", "konflikty-v-seme", "trudnosti-s-podrostkom", "poterya-blizkogo", "travmaticheskij-opyt", "adaptatsiya-pereezd", "prokrastinatsiya", "samoorganizatsiya", "navyazchivye-mysli", "psihosomatika"],
    },
    {
        id: "spec-50",
        firstName: "Ron",
        lastName: "Shapira",
        phoneNumber: "+972546234567",
        photoUrl: null,
        birthDate: "1989-08-28T00:00:00.000Z",
        gender: "male",
        languages: ["he", "en"],
        profession: "coach",
        meetingFormat: "online",
        sessionTypes: ["individual"],
        experience: 9,
        pricePerSession: 175,
        services: ["postanovka-tselej", "dostizhenie-tselej", "plan-dejstvij", "dolgosrochnoe-planirovanie", "tajm-menedzhment", "samodistsiplina", "prokrastinatsiya-kouching", "privychki-rutina", "kariernyj-rost", "smena-professii", "sobesedovaniya", "peregovory-zarplata", "adaptatsiya-novaya-rabota", "liderstvo", "upravlenie-komandoj", "delegirovanie", "prinyatie-reshenij", "biznes-kouching", "finansovye-tseli", "strategiya-razvitiya", "lichnyj-brend", "uverennost-kouching", "publichnye-vystupleniya", "kommunikatsiya-soft-skills", "lichnye-granitsy-obschenie", "work-life-balance", "energiya-resursnost", "profilaktika-vygoraniya"],
    },
];

export const specialistData: SpecialistDTO[] = baseSpecialistData.map(
    (specialist) => ({
        ...specialist,
        about: ABOUT_BY_PROFESSION[specialist.profession],
        workMethods: WORK_METHODS_BY_PROFESSION[specialist.profession],
        mainDegree: MAIN_DEGREE_BY_PROFESSION[specialist.profession],
        additionalDegrees:
            ADDITIONAL_DEGREES_BY_PROFESSION[specialist.profession],
        values: VALUES_BY_PROFESSION[specialist.profession],
    }),
);
