import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

import AppBread from '@/components/blocks/nav/app-bread';


import SpecialistSidebar from '@/components/spicialist-sidebar/specialist-sidebar';

const roboto = Roboto({
    variable: '--font-roboto',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={`${roboto.variable} antialiased **:font-mono flex h-screen overflow-hidden bg-primary/25 `}>
            <SpecialistSidebar />
            <div className="flex flex-col flex-1">
                <main className="flex-1 min-h-0 h-full ">
                    {children}
                </main>
            </div>
        </div>
    );
}
