import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

import AppBread from '@/components/blocks/nav/app-bread';


import SpecialistSidebar from '@/components/spicialist-sidebar/specialist-sidebar';

const roboto = Roboto({
    variable: '--font-roboto',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={`${roboto.variable} antialiased **:font-mono flex h-screen overflow-hidden`}>
            <SpecialistSidebar />
            <div className="flex flex-col flex-1 overflow-hidden">
                <div className="bg-primary/80 border-sidebar-border flex h-12 shrink-0 items-center border-b px-4 shadow-[inset_0_0_10px_0] shadow-black/10 z-10">
                    <AppBread />
                </div>
                <main className="flex-1 overflow-auto">
                    {children}
                </main>
            </div>
        </div>
    );
}
