import { AppSidebar } from '@/components/blocks/nav/app-sidebar';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

import AppBread from '@/components/blocks/nav/app-bread';

import { Separator } from '@/components/ui/separator';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-hidden">
      <body
        className={`${roboto.variable} antialiased **:font-mono`}
        dir='rtl'
      >
        <SidebarProvider>
          <AppSidebar />
          <div className="flex max-h-screen flex-1 flex-col">
            <div className="bg-sidebar border-sidebar-border flex h-full max-h-[48.4px] w-full items-center justify-between border-b p-2">
              <div className="flex items-center gap-2">
                <SidebarTrigger className="size-8 cursor-pointer" />
                <Separator orientation="vertical" className="mr-2 h-4!" />
                <AppBread />
              </div>

              {/* <div className="flex items-center gap-2 *:cursor-pointer">
                <LanguagePicker />
              </div> */}
            </div>
            <section className="custom-scrollbar relative flex max-h-[clac(100%-48.4px)] max-w-svw flex-1 overflow-auto shadow-[inset_0_0_10px_0] shadow-black/10">
              {children}
            </section>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
