import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Header } from "../../components/header/Header";
import MainProvider from "@/components/providers/MainProvider";
import { Toaster } from "@/components/ui/sonner";
import { Ubuntu } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const ubuntu = Ubuntu({
    subsets: ["latin", "cyrillic"],
    variable: "--font-ubuntu",
    weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${ubuntu.variable} font-sans antialiased h-screen flex flex-col max-h-screen relative w-full`}
            >
                <MainProvider>
                    <Header />
                    {children}
                    <Toaster
                        richColors
                        closeButton
                        theme="light"
                        visibleToasts={2}
                    />
                </MainProvider>
            </body>
        </html>
    );
}
