import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Header } from "../../components/header/Header";
import "./globals.css";
import AuthProvider from "@/components/providers/AuthProvider";
import MainProvider from "@/components/providers/MainProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex flex-col max-h-screen relative`}
            >
                <MainProvider>
                    <Header />
                    {children}
                </MainProvider>
            </body>
        </html>
    );
}
