import type { SpecialistDTO } from "@/features/specialist/model/types";

type SpecialistMock = SpecialistDTO;

export const specialistData: SpecialistMock[] = [
    {
        id: "spec-1",
        firstName: "Maya",
        lastName: "Levi",
        phoneNumber: "+972501234567",
        photoUrl: null,
        birthDate: "2024-06-10T09:00:00.000Z",
        gender: "female",
        languages: ["he", "en"],
        profession: "psychologist",
        meetingFormat: "online",
        experience: 9,
        services: ["Anxiety", "Stress", "PTSD"],
    },
    {
        id: "spec-2",
        firstName: "Alex",
        lastName: "Petrov",
        phoneNumber: "+972541234567",
        photoUrl: null,
        birthDate: "2024-06-10T09:00:00.000Z",
        gender: "male",
        languages: ["ru", "en"],
        profession: "therapist",
        meetingFormat: "online",
        experience: 12,
        services: ["Depression", "Burnout", "Self-esteem"],
    },
    {
        id: "spec-3",
        firstName: "Nadia",
        lastName: "Koval",
        phoneNumber: "+972521234567",
        photoUrl: null,
        birthDate: "2024-06-10T09:00:00.000Z",
        gender: "female",
        languages: ["uk", "ru"],
        profession: "coach",
        meetingFormat: "offline",
        experience: 6,
        services: ["Life goals", "Career", "Motivation"],
    },
    {
        id: "spec-4",
        firstName: "Omar",
        lastName: "Hassan",
        phoneNumber: "+972531234567",
        photoUrl: null,
        birthDate: "2024-06-10T09:00:00.000Z",
        gender: "male",
        languages: ["ar", "en"],
        profession: "therapist",
        meetingFormat: "online",
        experience: 10,
        services: ["Family therapy", "Relationships", "Anger"],
    },
    {
        id: "spec-5",
        firstName: "Lina",
        lastName: "Cohen",
        phoneNumber: "+972551234567",
        photoUrl: null,
        birthDate: "2024-06-10T09:00:00.000Z",
        gender: "female",
        languages: ["he", "ru", "en"],
        profession: "psychologist",
        meetingFormat: "offline",
        experience: 8,
        services: ["Trauma", "Sleep", "Mindfulness"],
    },
];
