import type { PatientViewResponse } from "@/features/patient-view/model/types";

const now = new Date();

function daysFromNow(days: number, hours = 10, minutes = 0): string {
    const d = new Date(now);
    d.setDate(d.getDate() + days);
    d.setHours(hours, minutes, 0, 0);
    return d.toISOString();
}

function daysAgo(days: number, hours = 10, minutes = 0): string {
    return daysFromNow(-days, hours, minutes);
}

const patientViewMockMap: Record<string, PatientViewResponse> = {
    "patient-1": {
        patient: {
            id: "patient-1",
            firstName: "יוסי",
            lastName: "כהן",
            photoUrl: "https://picsum.photos/seed/p1/200",
            birthDate: "1985-03-14",
            gender: "male",
            languages: ["he", "ru"],
            phoneNumber: "+972501234567",
        },
        sessions: [
            {
                id: "p1-s1",
                userId: "patient-1",
                specialistId: "specialist-1",
                startAt: daysFromNow(14, 10, 0),
                endAt: daysFromNow(14, 10, 50),
                date: daysFromNow(14, 10, 0),
                status: "upcoming",
                createdAt: daysAgo(7, 8, 0),
                income: 350,
                meetingUrl: "https://meet.example.com/p1-s1",
                type: "individual",
            },
            {
                id: "p1-s2",
                userId: "patient-1",
                specialistId: "specialist-1",
                startAt: daysAgo(30, 9, 0),
                endAt: daysAgo(30, 9, 50),
                date: daysAgo(30, 9, 0),
                status: "completed",
                createdAt: daysAgo(44, 8, 0),
                income: 350,
                meetingUrl: "https://meet.example.com/p1-s2",
                type: "individual",
            },
            {
                id: "p1-s3",
                userId: "patient-1",
                specialistId: "specialist-1",
                startAt: daysAgo(55, 11, 0),
                endAt: daysAgo(55, 11, 50),
                date: daysAgo(55, 11, 0),
                status: "completed",
                createdAt: daysAgo(69, 8, 0),
                income: 350,
                meetingUrl: "https://meet.example.com/p1-s3",
                type: "individual",
            },
            {
                id: "p1-s4",
                userId: "patient-1",
                specialistId: "specialist-1",
                startAt: daysAgo(96, 14, 0),
                endAt: daysAgo(96, 14, 50),
                date: daysAgo(96, 14, 0),
                status: "canceled",
                createdAt: daysAgo(110, 8, 0),
                income: 0,
                meetingUrl: undefined,
                type: "individual",
            },
            {
                id: "p1-s5",
                userId: "patient-1",
                specialistId: "specialist-1",
                startAt: daysAgo(130, 9, 0),
                endAt: daysAgo(130, 9, 50),
                date: daysAgo(130, 9, 0),
                status: "completed",
                createdAt: daysAgo(144, 8, 0),
                income: 350,
                meetingUrl: "https://meet.example.com/p1-s5",
                type: "individual",
            },
        ],
    },

    "patient-2": {
        patient: {
            id: "patient-2",
            firstName: "מיכל",
            lastName: "לוי",
            photoUrl: "https://picsum.photos/seed/p2/200",
            birthDate: "1992-07-22",
            gender: "female",
            languages: ["he"],
            phoneNumber: "+972527654321",
        },
        sessions: [
            {
                id: "p2-s1",
                userId: "patient-2",
                specialistId: "specialist-1",
                startAt: daysFromNow(7, 10, 0),
                endAt: daysFromNow(7, 10, 50),
                date: daysFromNow(7, 10, 0),
                status: "upcoming",
                createdAt: daysAgo(3, 8, 0),
                income: 350,
                meetingUrl: "https://meet.example.com/p2-s1",
                type: "individual",
            },
            {
                id: "p2-s2",
                userId: "patient-2",
                specialistId: "specialist-1",
                startAt: daysAgo(21, 10, 0),
                endAt: daysAgo(21, 10, 50),
                date: daysAgo(21, 10, 0),
                status: "completed",
                createdAt: daysAgo(35, 8, 0),
                income: 350,
                meetingUrl: "https://meet.example.com/p2-s2",
                type: "couple",
            },
            {
                id: "p2-s3",
                userId: "patient-2",
                specialistId: "specialist-1",
                startAt: daysAgo(49, 10, 0),
                endAt: daysAgo(49, 10, 50),
                date: daysAgo(49, 10, 0),
                status: "completed",
                createdAt: daysAgo(63, 8, 0),
                income: 350,
                meetingUrl: "https://meet.example.com/p2-s3",
                type: "individual",
            },
            {
                id: "p2-s4",
                userId: "patient-2",
                specialistId: "specialist-1",
                startAt: daysAgo(70, 10, 0),
                endAt: daysAgo(70, 10, 50),
                date: daysAgo(70, 10, 0),
                status: "canceled",
                createdAt: daysAgo(84, 8, 0),
                income: 0,
                meetingUrl: undefined,
                type: "couple",
            },
        ],
    },

    "patient-3": {
        patient: {
            id: "patient-3",
            firstName: "דנה",
            lastName: "אברהם",
            photoUrl: "https://picsum.photos/seed/p3/200",
            birthDate: "1998-11-05",
            gender: "female",
            languages: ["he", "en"],
            phoneNumber: "+972541112233",
        },
        sessions: [
            {
                id: "p3-s1",
                userId: "patient-3",
                specialistId: "specialist-1",
                startAt: daysFromNow(21, 11, 30),
                endAt: daysFromNow(21, 12, 20),
                date: daysFromNow(21, 11, 30),
                status: "upcoming",
                createdAt: daysAgo(1, 8, 0),
                income: 350,
                meetingUrl: "https://meet.example.com/p3-s1",
                type: "individual",
            },
            {
                id: "p3-s2",
                userId: "patient-3",
                specialistId: "specialist-1",
                startAt: daysAgo(14, 11, 30),
                endAt: daysAgo(14, 12, 20),
                date: daysAgo(14, 11, 30),
                status: "completed",
                createdAt: daysAgo(28, 8, 0),
                income: 350,
                meetingUrl: "https://meet.example.com/p3-s2",
                type: "individual",
            },
            {
                id: "p3-s3",
                userId: "patient-3",
                specialistId: "specialist-1",
                startAt: daysAgo(42, 11, 0),
                endAt: daysAgo(42, 11, 50),
                date: daysAgo(42, 11, 0),
                status: "canceled",
                createdAt: daysAgo(56, 8, 0),
                income: 0,
                meetingUrl: undefined,
                type: "individual",
            },
        ],
    },

    "patient-4": {
        patient: {
            id: "patient-4",
            firstName: "אבי",
            lastName: "שמעון",
            photoUrl: "https://picsum.photos/seed/p4/200",
            birthDate: "1979-01-30",
            gender: "male",
            languages: ["he"],
            phoneNumber: "+972509988776",
        },
        sessions: [
            {
                id: "p4-s1",
                userId: "patient-4",
                specialistId: "specialist-1",
                startAt: daysFromNow(5, 14, 0),
                endAt: daysFromNow(5, 14, 50),
                date: daysFromNow(5, 14, 0),
                status: "upcoming",
                createdAt: daysAgo(2, 8, 0),
                income: 350,
                meetingUrl: "https://meet.example.com/p4-s1",
                type: "couple",
            },
            {
                id: "p4-s2",
                userId: "patient-4",
                specialistId: "specialist-1",
                startAt: daysAgo(25, 14, 0),
                endAt: daysAgo(25, 14, 50),
                date: daysAgo(25, 14, 0),
                status: "completed",
                createdAt: daysAgo(39, 8, 0),
                income: 350,
                meetingUrl: "https://meet.example.com/p4-s2",
                type: "couple",
            },
            {
                id: "p4-s3",
                userId: "patient-4",
                specialistId: "specialist-1",
                startAt: daysAgo(60, 14, 0),
                endAt: daysAgo(60, 14, 50),
                date: daysAgo(60, 14, 0),
                status: "completed",
                createdAt: daysAgo(74, 8, 0),
                income: 350,
                meetingUrl: "https://meet.example.com/p4-s3",
                type: "couple",
            },
        ],
    },

    "patient-5": {
        patient: {
            id: "patient-5",
            firstName: "רחל",
            lastName: "גולן",
            photoUrl: "https://picsum.photos/seed/p5/200",
            birthDate: "2001-09-17",
            gender: "female",
            languages: ["he", "en"],
            phoneNumber: "+972523344556",
        },
        sessions: [
            {
                id: "p5-s1",
                userId: "patient-5",
                specialistId: "specialist-1",
                startAt: daysFromNow(10, 15, 30),
                endAt: daysFromNow(10, 16, 20),
                date: daysFromNow(10, 15, 30),
                status: "upcoming",
                createdAt: daysAgo(5, 8, 0),
                income: 350,
                meetingUrl: "https://meet.example.com/p5-s1",
                type: "individual",
            },
            {
                id: "p5-s2",
                userId: "patient-5",
                specialistId: "specialist-1",
                startAt: daysAgo(18, 15, 30),
                endAt: daysAgo(18, 16, 20),
                date: daysAgo(18, 15, 30),
                status: "completed",
                createdAt: daysAgo(32, 8, 0),
                income: 350,
                meetingUrl: "https://meet.example.com/p5-s2",
                type: "individual",
            },
        ],
    },

    "patient-6": {
        patient: {
            id: "patient-6",
            firstName: "נועם",
            lastName: "ברק",
            photoUrl: "https://picsum.photos/seed/p6/200",
            birthDate: "1990-04-08",
            gender: "male",
            languages: ["he", "ru"],
            phoneNumber: "+972536677889",
        },
        sessions: [
            {
                id: "p6-s1",
                userId: "patient-6",
                specialistId: "specialist-1",
                startAt: daysFromNow(3, 17, 0),
                endAt: daysFromNow(3, 17, 50),
                date: daysFromNow(3, 17, 0),
                status: "upcoming",
                createdAt: daysAgo(10, 8, 0),
                income: 350,
                meetingUrl: "https://meet.example.com/p6-s1",
                type: "individual",
            },
            {
                id: "p6-s2",
                userId: "patient-6",
                specialistId: "specialist-1",
                startAt: daysAgo(35, 17, 0),
                endAt: daysAgo(35, 17, 50),
                date: daysAgo(35, 17, 0),
                status: "completed",
                createdAt: daysAgo(49, 8, 0),
                income: 350,
                meetingUrl: "https://meet.example.com/p6-s2",
                type: "individual",
            },
            {
                id: "p6-s3",
                userId: "patient-6",
                specialistId: "specialist-1",
                startAt: daysAgo(70, 17, 0),
                endAt: daysAgo(70, 17, 50),
                date: daysAgo(70, 17, 0),
                status: "canceled",
                createdAt: daysAgo(84, 8, 0),
                income: 0,
                meetingUrl: undefined,
                type: "individual",
            },
        ],
    },

    "patient-7": {
        patient: {
            id: "patient-7",
            firstName: "נועם",
            lastName: "גולן",
            photoUrl: "https://picsum.photos/seed/p7/200",
            birthDate: "2009-06-25",
            gender: "male",
            languages: ["he"],
            phoneNumber: "+972548899001",
        },
        sessions: [
            {
                id: "p7-s1",
                userId: "patient-7",
                specialistId: "specialist-1",
                startAt: daysFromNow(28, 18, 0),
                endAt: daysFromNow(28, 18, 50),
                date: daysFromNow(28, 18, 0),
                status: "upcoming",
                createdAt: daysAgo(10, 8, 0),
                income: 350,
                meetingUrl: undefined,
                type: "teen",
            },
            {
                id: "p7-s2",
                userId: "patient-7",
                specialistId: "specialist-1",
                startAt: daysAgo(28, 18, 0),
                endAt: daysAgo(28, 18, 50),
                date: daysAgo(28, 18, 0),
                status: "completed",
                createdAt: daysAgo(42, 8, 0),
                income: 350,
                meetingUrl: undefined,
                type: "teen",
            },
        ],
    },
};

export function getPatientViewMock(patientId: string): PatientViewResponse | null {
    return patientViewMockMap[patientId] ?? null;
}
